### ISSUE TITLE
Implementation Wishlist: Implement that parameters can be read from wrapper

### ISSUE THREAD

**Issue by eggimasv** [nismod/smif#110]
Implement that the parameters definition in sector_model files can be accessed from wrapper

**Comment by tomalrussell** [comment]
Have a look at the `data` parameter that gets passed to `SectorModel.simulate()` - it should contain both parameters and data from any dependencies, something like:

```python
{
    'parameter_name': 3.0,
    'data_name': <nd.array>
}
```
