### ISSUE TITLE
data_handle.set_results() function

### ISSUE THREAD

**Issue by eggimasv** [nismod/smif#139]
- I would recommend using np.result() and np.load() instead of writing to CSV for the set_result() function
- If we go for CSV there needs to be removed the extra lines which are generated when writing to file
- I would also recommend deleting previous model runs if the same model run is run twice

**Comment by RoaldL** [comment]
Thanks for reporting this Sven. I have created items for this in our issue tracking system.
#155325112
#155325091
#155325066
