### ISSUE TITLE
Submit to open source software journal

### ISSUE THREAD

**Issue by tomalrussell** [nismod/smif#300]
Possible candidates include:

- https://openresearchsoftware.metajnl.com/
- http://joss.theoj.org/

**Comment by martinjrobins** [comment]
We have put in a paper at JORS. The wait time for review has not been good (2-3 months now I think), but I think that is because an editor quit, so I'm willing to give them the benefit of the doubt. JORS seems much more involved in the UK RSE community

**Comment by willu47** [comment]
Paper submitted today and in review.
