### ISSUE TITLE
Built in adaptors call ndim on DataArray

### ISSUE THREAD

**Issue by willu47** [nismod/smif#317]
This causes the following error:

```
AttributeError: 'DataArray' object has no attribute 'ndim'
```

Reported by @LahiruJayasuriya 

The problem is caused by `Adaptor.simulate` passing a `DataArray` to `Adaptor.convert` where convert is expecting an `ndarray`.

Need to fix the tests, which currently pass in numpy ndarray rather than smif DataArray objects.

**Comment by tomalrussell** [comment]
Closed by #318
