### ISSUE TITLE
Fail to read input data when source/sink names don't match

### ISSUE THREAD

**Issue by tomalrussell** [nismod/smif#321]
Manifests as a data reading error (thanks @LahiruJayasuriya for the pointers):

```
FileNotFoundError: 
Fileb'.\\results\\energy_supply_demand\\energy_demand_constrained\\decision_0\\output_service_gas_district_heating_gas_timestep_2050.csv' does not exist
```

However, there *is* `output_service_gas_district_heating_CHP_gas_timestep_2050.csv` in `./results/energy_demand_constrained/decision_0`

The dependency in this case has a mismatch in the names:
```
- sink: convert_regions_ed_to_es
  source: energy_demand_constrained
  sink_input: service_gas_district_heating_gas
  source_output: service_gas_district_heating_CHP_gas
```

in `sos_models/energy_supply_demand_update.yml`

May be related to #316 (both to do with Spec/DataArray names)

**Comment by willu47** [comment]
@tomalrussell - not that the model runs and paths are different to one another. The second is a run of the `energy_demand_constrained` model run run in isolation, the first is a run of the `energy_supply_demand` model run.

**Comment by tomalrussell** [comment]
@willu47 Lahiru can confirm that the run of `energy_demand_constrained` within the `energy_supply_demand` model run does produce service_gas_district_heating_CHP_gas outputs at `.\\results\\energy_supply_demand\\energy_demand_constrained\\decision_0\\output_service_gas_district_heating_gas_CHP_timestep_2050.csv`

Here's a minimal example - may be suitable for integration test: [input_output.zip](https://github.com/nismod/smif/files/2941682/input_output.zip)
