### ISSUE TITLE
Filestore: error trying to read current interventions when state is empty

### ISSUE THREAD

**Issue by tomalrussell** [nismod/smif#368]
in wrapper:
```
data_handle.get_current_interventions()
```
raises `pandas.errors.EmptyDataError: No columns to parse from file` if nothing was written to the state file

**Comment by willu47** [comment]
Fixed in develop branch?

**Comment by tomalrussell** [comment]
Yes - duplicate of https://github.com/nismod/smif/issues/345 !

**Comment by tomalrussell** [comment]
Fixed by #354
